#!/bin/bash
(  wget -q -O /mnt/alexandria/podcasts/$1-$(date +%Y%m%d).mp3 http://www.live365.com/play/304480 &
   sleep $2
   kill $!) 2> /dev/null
xmms --enqueue /mnt/alexandria/podcasts/$1-$(date +%Y%m%d).mp3
